plugins:
  - package: ref://backstage-community-plugin-catalog-backend-module-keycloak
    enabled: false
  - package: ref://backstage-plugin-catalog-backend-module-github-org
    enabled: false
  - package: oci://quay.io/rh-ee-jhe/catalog-github-org-transformer:v0.3.0!internal-backstage-plugin-catalog-backend-module-github-org-transformer
    enabled: false
  - package: ref://backstage-plugin-catalog-backend-module-msgraph
    enabled: false
  - package: ref://backstage-community-plugin-rbac
    enabled: false
