name: E2E Bash

on:
  pull_request:
    branches:
      - 'main'
      - 'release-[0-9]+.[0-9]+'
    paths:
      - '.ci/**'

jobs:
  lint:
    name: ShellCheck and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        working-directory: ./.ci
        run: yarn install

      - name: Run ShellCheck check
        working-directory: ./.ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn shellcheck

      - name: Run Prettier check
        working-directory: ./.ci
        run: yarn prettier:check
