name: Update versions.md in Dynamic Plugins Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-[0-9]+.[0-9]+'
    paths:
      - "backstage.json"
      - "packages/app/package.json"
      - "packages/backend/package.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-versions-md:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"

      - name: Run update-versions-doc script
        run: node scripts/update-versions-doc.mjs docs/dynamic-plugins/versions.md "${{ github.ref_name }}"
        # Note: GITHUB_REPOSITORY is available as a default env var in the github runner

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(docs): Update versions.md in dynamic plugin documentation"
          branch: chore/automated-update-versions-doc-${{ github.ref_name }}
          title: "chore(docs): [${{ github.ref_name }}] Update versions.md in dynamic plugin documentation"
          body: "Updates Version Compatibility Matrix in dynamic plugin documentation"
          labels: "documentation"
          signoff: true
          delete-branch: true
